include: vstar_bench.yaml
task: "vstar_bench_molmo2_zs"
generation_kwargs:
  max_new_tokens: 12
  temperature: 0
  do_sample: False
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
